using System.Text.Json;
using Chargeback.Api.Common.Messaging;
using Chargeback.Api.Common.Results;
using Chargeback.Api.Common.Security;
using Chargeback.Api.Features.Intake.Contracts;
using Chargeback.Api.Features.Review.Decision;
using Chargeback.Infrastructure.Ai.Capabilities;
using Chargeback.Infrastructure.Persistence;
using Chargeback.Infrastructure.Persistence.Entities;
using Chargeback.Infrastructure.Persistence.Queries;
using Chargeback.SharedKernel.Results;
using Chargeback.SharedKernel.ValueObjects;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace Chargeback.Api.Features.Review.Summary;

public enum ReviewSummaryOutcome
{
    /// <summary>The summary was generated and stored.</summary>
    Generated,

    /// <summary>A summary was already stored; it is never regenerated.</summary>
    AlreadySummarized,

    /// <summary>No deterministic result to explain: no completed triage outcome or no derived reason code.</summary>
    NothingToExplain,

    /// <summary>AI disabled, unavailable or invalid (fail-soft). Nothing stored; the case proceeds without a summary.</summary>
    AiUnavailable,
}

/// <summary>
/// Generates the plain-English review summary once, when a case first enters review (common guide §6 Act 5). The
/// Analysis &amp; Explanation agent only explains the existing deterministic result. Not transactional: the model call
/// must happen outside any database transaction. Idempotent per source event (<c>processed_domain_events</c>) and per
/// case (the summary is written only while <c>cases.ai_summary</c> is empty). No automatic retry when AI is
/// unavailable; an explicit regeneration operation would need its own specification.
/// </summary>
[SystemOperation("The review summary is generated by the workflow when a case enters review, never on request.")]
[NotBankScoped("Workflow step for one case chosen by the workflow; the summary belongs to that case's bank.")]
public sealed record GenerateReviewSummaryCommand(Guid CaseId, Guid SourceEventId, string Consumer) : ICommand<ReviewSummaryOutcome>;

internal sealed class GenerateReviewSummaryHandler(
    ChargebackDbContext db, IDapperQueryService queries, IDisputeReader disputes, ITriageSummarizer summarizer, TimeProvider timeProvider)
    : IRequestHandler<GenerateReviewSummaryCommand, Result<ReviewSummaryOutcome>>
{
    // Facts already decided deterministically: derived reason code, deadline, latest triage outcome and the required
    // documents recorded by that triage run (triage.completed scheme audit).
    private const string FactsSql = """
        SELECT c.id, c.dispute_id, d.bank_id, c.ai_summary, c.filing_deadline_date, rc.code AS reason_code, t.outcome,
               (SELECT (e.event_data->'data'->'scheme'->'requiredDocuments')::text
                FROM chargeback_diagram.domain_events e
                WHERE e.case_id = c.id AND e.event_type = 'triage.completed'
                ORDER BY e.created_at DESC, e.id DESC LIMIT 1) AS required_documents
        FROM chargeback_diagram.cases c
        JOIN chargeback_diagram.disputes d ON d.id = c.dispute_id
        LEFT JOIN chargeback_diagram.scheme_reason_codes rc ON rc.id = c.derived_reason_code
        LEFT JOIN LATERAL (
          SELECT tr.outcome FROM chargeback_diagram.triage_results tr
          WHERE tr.case_id = c.id ORDER BY tr.created_at DESC, tr.id DESC LIMIT 1) t ON true
        WHERE c.id = @CaseId
        """;

    public async Task<Result<ReviewSummaryOutcome>> Handle(GenerateReviewSummaryCommand request, CancellationToken cancellationToken)
    {
        if (await db.ProcessedDomainEvents.AnyAsync(p => p.EventId == request.SourceEventId, cancellationToken))
        {
            return ReviewErrors.AlreadyProcessed;
        }

        var facts = await queries.QuerySingleOrDefaultAsync<Facts>(FactsSql, new { request.CaseId }, cancellationToken);
        if (facts is null)
        {
            return Errors.ResourceNotFound;
        }

        var outcome = await SummarizeAsync(facts, cancellationToken);

        db.ProcessedDomainEvents.Add(new ProcessedDomainEvent
        {
            EventId = request.SourceEventId,
            Consumer = request.Consumer,
            ProcessedAt = timeProvider.GetUtcNow(),
        });
        try
        {
            await db.SaveChangesAsync(cancellationToken);
        }
        catch (DbUpdateException ex) when (ex.InnerException is PostgresException { SqlState: PostgresErrorCodes.UniqueViolation })
        {
            return ReviewErrors.AlreadyProcessed;
        }

        return outcome;
    }

    private async Task<ReviewSummaryOutcome> SummarizeAsync(Facts facts, CancellationToken cancellationToken)
    {
        if (facts.AiSummary is not null)
        {
            return ReviewSummaryOutcome.AlreadySummarized;
        }

        if (facts.ReasonCode is null || facts.Outcome is null)
        {
            return ReviewSummaryOutcome.NothingToExplain;
        }

        var now = timeProvider.GetUtcNow();
        var gates = (await disputes.ReadGatesAsync(facts.DisputeId, cancellationToken))
            .Select(g => new GateResult(g.GateNumber, g.GateName, g.Passed, g.FlagReason, g.CheckedAt ?? now))
            .ToArray();
        var result = await summarizer.SummarizeAsync(
            new TriageSummaryInput(
                facts.Id,
                facts.BankId,
                facts.ReasonCode,
                facts.FilingDeadlineDate,
                Enum.Parse<TriageOutcome>(facts.Outcome),
                gates,
                RequiredSlotNames(facts.RequiredDocuments)),
            cancellationToken);
        if (!result.IsSuccess)
        {
            return ReviewSummaryOutcome.AiUnavailable;
        }

        // Written once: only while empty, so a concurrent or repeated run never overwrites the stored text.
        var written = await db.Cases
            .Where(c => c.Id == facts.Id && c.AiSummary == null)
            .ExecuteUpdateAsync(s => s.SetProperty(c => c.AiSummary, result.Output!.SummaryText), cancellationToken);
        return written == 1 ? ReviewSummaryOutcome.Generated : ReviewSummaryOutcome.AlreadySummarized;
    }

    private static string[] RequiredSlotNames(string? json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            return [];
        }

        using var document = JsonDocument.Parse(json);
        return document.RootElement.ValueKind != JsonValueKind.Array
            ? []
            : document.RootElement.EnumerateArray()
                .Select(d => d.TryGetProperty("slotName", out var name) ? name.GetString() : null)
                .OfType<string>()
                .ToArray();
    }

    private sealed class Facts
    {
        public Guid Id { get; set; }

        public Guid DisputeId { get; set; }

        public Guid BankId { get; set; }

        public string? AiSummary { get; set; }

        public DateOnly? FilingDeadlineDate { get; set; }

        public string? ReasonCode { get; set; }

        public string? Outcome { get; set; }

        public string? RequiredDocuments { get; set; }
    }
}
